import * as Url from "./url";
import * as Type from "./type";
import * as Time from "./time";
import * as UI from "./ui";
import * as Model from "./model";
import * as View from "./view";
import * as Event from "./event";
import * as Ruler from "./ruler";
import * as Render from "./render";
import config from "@resource/config.json";
import * as JsonEvalUpdater from "./json-eval-updater";
console.log("🚀 Slide Rule build script");
Type;
Url.initialize();
Time.initialize();
UI.initialize();
Model.initialize();
View.initialize();
Event.initialize();
Ruler.initialize();
Render.setRenderer(Ruler.renderer);
Render.markDirty();
(window as any)["Type"] = Type;
(window as any)["Url"] = Url;
(window as any)["Time"] = Time;
(window as any)["UI"] = UI;
(window as any)["Model"] = Model;
(window as any)["View"] = View;
(window as any)["Event"] = Event;
(window as any)["Ruler"] = Ruler;
(window as any)["Render"] = Render;
(window as any)["config"] = config;
(window as any)["updateJsonWithEval"] = (json: string) =>
    console.log(`Updated JSON with eval:`, JSON.stringify(JsonEvalUpdater.updateJsonWithEval(JSON.parse(json))));
